apiVersion: apps/v1
kind: Deployment
metadata:
    name: payment 
    labels:
        app: payment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: payment
    template:
        metadata:
            labels:
                app: payment
        spec:
            containers:
            - name: payment
              image: 712351274497.dkr.ecr.ap-northeast-2.amazonaws.com/payment:latest
              ports:
              - containerPort: 8084
              resources:
                  requests:
                      cpu: "100m"
                  limits:
                      cpu: "200m"