apiVersion: v1
kind: Service
metadata:
    name: payment
    labels:
        run: payment
spec:
    ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
    selector:
        run: payment
    type: LoadBalancer 
